### ISSUE TITLE
Rf historic "MySQLdb._exceptions.ProgrammingError: (1146, "Table 'robothistoric.tb_project' doesn't exist")"

### ISSUE THREAD

**Issue by vikitech83** [adiralashiva8/robotframework-historic#19]
using ubuntu with mysql.
superuser and db table created succesfully.
Get Started on RFhistoric 

$ rfhistoric
 * Serving Flask app "robotframework_historic.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [01/Jul/2020 14:12:33] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Jul/2020 14:12:35] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Jul/2020 14:12:35] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Jul/2020 14:12:35] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Jul/2020 14:12:35] "GET / HTTP/1.1" 200 -
[2020-07-01 14:12:41,428] ERROR in app: Exception on /home [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/robotframework_historic/app.py", line 22, in home
    cursor.execute("select * from tb_project;")
  File "/usr/local/lib/python3.6/dist-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/dist-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'robothistoric.tb_project' doesn't exist")
127.0.0.1 - - [01/Jul/2020 14:12:41] "GET /home HTTP/1.1" 500 -

**Comment by adiralashiva8** [comment]
Thank you @vikitech83 for notifying issue, this is due to case sensitive issue in linux. Couple of users reported same issue & fix is available in master (not yet released). Please use following command to install latest changes (current issue fix)

`pip install git+https://github.com/adiralashiva8/robotframework-historic`

**Comment by vikitech83** [comment]
Used master from pip install git+https://github.com/adiralashiva8/robotframework-historic

mysql> CREATE DATABASE IF NOT EXISTS robothistoric;
Query OK, 1 row affected (0.00 sec)

mysql> USE robothistoric;
Database changed
mysql> Create table TB_PROJECT ( Project_Id INT NOT NULL auto_increment primary key, Project_Name TEXT, Project_Desc TEXT, Project_Image TEXT, Created_Date DATETIME, Last_Updated DATETIME, Total_Executions INT, Recent_Pass_Perc FLOAT, Overall_Pass_Perc FLOAT);
Query OK, 0 rows affected (0.06 sec)

and getting :MySQLdb._exceptions.ProgrammingError: (1146, "Table 'robothistoric.tb_project' doesn't exist")

rfhistoric
 * Serving Flask app "robotframework_historic.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2020-07-01 16:22:22,126] ERROR in app: Exception on /home [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/robotframework_historic/app.py", line 22, in home
    cursor.execute("select * from tb_project;")
  File "/usr/local/lib/python3.6/dist-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/dist-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'robothistoric.tb_project' doesn't exist")
127.0.0.1 - - [01/Jul/2020 16:22:22] "GET /home HTTP/1.1" 500 -

**Comment by adiralashiva8** [comment]
Sorry for inconvenience, From above logs I observed that new changes not yet installed in your local. 

Could you please try following steps

Step 1: Please uninstall robotframework-historic

`pip uninstall robotframework-historic`

Step 2: Install latest changes

`pip install git+https://github.com/adiralashiva8/robotframework-historic`

Step 3: Remove table with tb_project if exist

`mysql> Delete table tb_project`

Step 4: Create table TB_PROJECT

Note: For linux tb_project is not same as TB_PROJECT due to this we are facing this issue

**Comment by adiralashiva8** [comment]
Issue is fixed in `#v0.1.9`, please use latest version
