### ISSUE TITLE
Create Project In RF Historic is not pushed to remote mysql database

### ISSUE THREAD

**Issue by vikitech83** [adiralashiva8/robotframework-historic#22]
mysqldb and rfhistoric hosted on separate ubuntu vm

With mysql database on remote machine, when creating RF Project on http://0.0.0.0:5000/home, created project (e.g. project name 'remote') is not getting pushed to  remote mysqldb.

$ rfhistoricparser -o "output.xml" -s "qamysql01" -u "superuser" -p "xxxxxxx" -n "remote"
Capturing execution results, This may take few minutes...
1049 (42000): Unknown database 'remote'
Traceback (most recent call last):
  File "/home/viksingh/.local/bin/rfhistoricparser", line 11, in <module>
    sys.exit(main())
  File "/home/viksingh/.local/lib/python3.6/site-packages/robotframework_historic_parser/runner.py", line 72, in main
    generate_report(args)
  File "/home/viksingh/.local/lib/python3.6/site-packages/robotframework_historic_parser/rfhistoricparser.py", line 62, in generate_report
    result_id = insert_into_execution_table(mydb, rootdb, opts.executionname, total, passed, failed, elapsedtime, stotal, spass, sfail, opts.projectname)
  File "/home/viksingh/.local/lib/python3.6/site-packages/robotframework_historic_parser/rfhistoricparser.py", line 137, in insert_into_execution_table
    cursorObj = con.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'

#### on remote mysqldb ########
mysql> show tables;
+-------------------------+
| Tables_in_robothistoric |
+-------------------------+
| TB_PROJECT              |
+-------------------------+
1 row in set (0.00 sec)

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| robothistoric      |
| sys                |
+--------------------+
5 rows in set (0.00 sec)

mysql> show tables;
+-------------------------+
| Tables_in_robothistoric |
+-------------------------+
| TB_PROJECT              |
+-------------------------+
1 row in set (0.01 sec)

mysql>

**Comment by vikitech83** [comment]
I missed to specify remote database "host" as part of project creation https://github.com/adiralashiva8/robotframework-historic/wiki/3.-Create-Project-In-RF-Historic

$ rfhistoric --help
usage: rfhistoric [-h] [-s SQLHOST] [-u USERNAME] [-p PASSWORD] [-a APPHOST]

optional arguments:
  -h, --help            show this help message and exit

General:
  -s SQLHOST, --sqlhost SQLHOST
                        MySQL database host address (default: localhost)
  -u USERNAME, --username USERNAME
                        User name of MySQL database (default: superuser)
  -p PASSWORD, --password PASSWORD
                        Password of MySQL database (default: passw0rd)
  -a APPHOST, --apphost APPHOST
                        Flask app host address (default: 0.0.0.0)
