### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'cursor'

### ISSUE THREAD

**Issue by Kitty2014** [adiralashiva8/robotframework-historic#4]
rfhistoricparser -o "output.xml" -s "127.0.0.1:3306" -u "superuser" -p "passw0rd" -n "test" -e "Smoke test on v1.0"
<class 'Exception'>
Traceback (most recent call last):
  File "/Users/cloud/anaconda3/bin/rfhistoricparser", line 10, in <module>
    sys.exit(main())
  File "/Users/cloud/anaconda3/lib/python3.7/site-packages/robotframework_historic_parser/runner.py", line 65, in main
    generate_report(args)
  File "/Users/cloud/anaconda3/lib/python3.7/site-packages/robotframework_historic_parser/rfhistoricparser.py", line 50, in generate_report
    result_id = insert_into_results_mysql_table(mydb, date_now, opts.executionname, total, passed, failed, elapsedtime)
  File "/Users/cloud/anaconda3/lib/python3.7/site-packages/robotframework_historic_parser/rfhistoricparser.py", line 100, in insert_into_results_mysql_table
    cursorObj = con.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'

**Comment by Kitty2014** [comment]
[20190802_100125.zip](https://github.com/adiralashiva8/robotframework-historic/files/4180468/20190802_100125.zip)
the robot  xml report

**Comment by Kitty2014** [comment]
@adiralashiva8  All of the above errors are prompted through the tutorial settings. Check if mySQL database needs special settings or other problems

**Comment by adiralashiva8** [comment]
@Kitty2014 Thanks for using rfhistoric, similar query has explained here - https://groups.google.com/d/msg/robotframework-users/xXcqwEs7qMU/cXRJUiFvAwAJ

Do let me know if this doesnt work for you

**Comment by Kitty2014** [comment]
@adiralashiva8  
【1】localhost:
 rfhistoricparser -o "output.xml" -s "localhost" -u "superuser" -p "passw0rd" -n "test" -e "Smoke test on v1.0"
【2】remote mySQL
rfhistoricparser -o "output.xml" -s "192.168.1.134" -u "superuser" -p "passw0rd" -n "test" -e "Smoke test on v1.0"

Thanks for you greate help!

**Comment by adiralashiva8** [comment]
@Kitty2014 Hope this resolved your issue. Can you close this if so

⭐️ repo if you like it
